import React from 'react';
import { Container, Typography, Box, Divider } from '@mui/material';
import ResponsiveAppBar from '../components/ResponsiveAppBar';

function PrivacyPolicy() {
  const lastUpdated = "February 6, 2026"; // Data actualitzada

  return (
    <>
      <ResponsiveAppBar pages={[{ name: 'Home', rout: '/' }, { name: 'Public Quizzes', rout: '/publicQuizzes' }]} />
      <Container maxWidth="md" sx={{ marginTop: '3rem', marginBottom: '5rem', color: '#2b2d42' }}>
        <Typography variant="h3" component="h1" gutterBottom sx={{ fontWeight: 'bold' }}>
          Privacy Policy
        </Typography>
        <Typography variant="body2" sx={{ color: 'text.secondary', mb: 4 }}>
          Last updated: {lastUpdated}
        </Typography>

        <Divider sx={{ mb: 4 }} />

        {/* 1. Introduction */}
        <Box sx={{ mt: 4 }}>
          <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
            1. Introduction
          </Typography>
          <Typography variant="body1" paragraph>
            Welcome to <strong>Quiz Generator</strong>. We value your privacy and are committed to being transparent about how we handle your data. This policy explains how we collect and process information when you use our service, which is hosted on Google Cloud and utilizes OpenAI's technology.
          </Typography>
        </Box>

        {/* 2. Information We Collect */}
        <Box sx={{ mt: 4 }}>
          <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
            2. Information We Collect
          </Typography>
          <Typography variant="body1" paragraph>
            We only collect the data necessary to provide the service and manage usage limits:
          </Typography>
          <Box component="ul" sx={{ pl: 2 }}>
            <li>
              <Typography variant="body1" sx={{ mb: 1 }}>
                <strong>Google Account Information:</strong> When you sign in via Google OAuth, we receive your <strong>email address, full name, and profile picture</strong>.
              </Typography>
            </li>
            <li>
              <Typography variant="body1" sx={{ mb: 1 }}>
                <strong>User-Generated Content:</strong> We store the quiz topics you provide and the resulting quizzes generated by the AI.
              </Typography>
            </li>
            <li>
              <Typography variant="body1">
                <strong>Usage Metadata:</strong> We keep track of the number of quizzes you generate daily to enforce our fair usage limits (e.g., 5 personal quizzes per day).
              </Typography>
            </li>
          </Box>
        </Box>

        {/* 3. Third-Party Service Providers */}
        <Box sx={{ mt: 4 }}>
          <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
            3. Third-Party Service Providers
          </Typography>
          <Typography variant="body1" paragraph>
            To operate this application, we share specific data with trusted third parties:
          </Typography>
          <Box component="ul" sx={{ pl: 2 }}>
            <li>
              <Typography variant="body1" sx={{ mb: 1 }}>
                <strong>OpenAI:</strong> The topics you enter are sent to OpenAI to generate quiz content. <strong>No personal identifying information</strong> (like your name or email) is ever sent to OpenAI.
              </Typography>
            </li>
            <li>
              <Typography variant="body1" sx={{ mb: 1 }}>
                <strong>Google Cloud Platform:</strong> Our application and authentication systems are hosted on Google Cloud (Region: europe-west1).
              </Typography>
            </li>
            <li>
              <Typography variant="body1">
                <strong>MongoDB Atlas:</strong> Your quizzes and basic profile data are securely stored in MongoDB Atlas databases.
              </Typography>
            </li>
          </Box>
        </Box>

        {/* 4. Data Retention and Deletion */}
        <Box sx={{ mt: 4 }}>
          <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
            4. Data Retention and Deletion
          </Typography>
          <Typography variant="body1" paragraph>
            We retain your information as long as your account is active. You have the right to request the deletion of your data at any time.
          </Typography>
          <Typography variant="body1">
            If you wish to delete your account and all associated quizzes, please contact us at the email address provided below. We will process your request within 72 hours.
          </Typography>
        </Box>

        {/* 5. AI Disclaimer */}
        <Box sx={{ mt: 4 }}>
          <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
            5. AI-Generated Content
          </Typography>
          <Typography variant="body1" paragraph>
            Please note that quizzes are generated by Artificial Intelligence. While we strive for accuracy, we are not responsible for incorrect information, biases, or errors in the content generated by the AI models.
          </Typography>
        </Box>

        {/* 6. Contact Us */}
        <Box sx={{ mt: 6, p: 3, bgcolor: 'rgba(127, 255, 212, 0.05)', borderRadius: '1rem', border: '1px solid rgba(127, 255, 212, 0.2)' }}>
          <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
            6. Contact Us
          </Typography>
          <Typography variant="body1">
            For any questions regarding your privacy, data deletion, or technical support, please reach out to:
          </Typography>
          <Typography variant="body1" sx={{ fontWeight: 'bold', mt: 1, color: '#051923' }}>
            support@liamviader.com
          </Typography>
        </Box>
      </Container>
    </>
  );
}

export default PrivacyPolicy;